steps:
- name: gcr.io/cloud-builders/go
  id: Compile application
  args:
  - build
  - -o
  - main
  - main.go

- name: gcr.io/cloud-builders/docker
  id: Build Docker image
  args:
  - build
  - -t
  - us-east1-docker.pkg.dev/qwiklabs-gcp-04-cf856ac77b68/my-repository/hello-cloudbuild-dev:v1.0
  - .

- name: gcr.io/cloud-builders/docker
  id: Push Docker image
  args:
  - push
  - us-east1-docker.pkg.dev/qwiklabs-gcp-04-cf856ac77b68/my-repository/hello-cloudbuild-dev:v1.0

- name: gcr.io/cloud-builders/gcloud
  id: Get GKE credentials
  args:
  - container
  - clusters
  - get-credentials
  - hello-cluster
  - --zone
  - us-east1-b
  - --project
  - qwiklabs-gcp-04-cf856ac77b68

- name: gcr.io/cloud-builders/kubectl
  id: Deploy development
  args:
  - apply
  - -f
  - dev/deployment.yaml
  env:
  - CLOUDSDK_COMPUTE_ZONE=us-east1-b
  - CLOUDSDK_CONTAINER_CLUSTER=hello-cluster

images:
- us-east1-docker.pkg.dev/qwiklabs-gcp-04-cf856ac77b68/my-repository/hello-cloudbuild-dev:v1.0

options:
  logging: CLOUD_LOGGING_ONLY
